In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cmath 
import seaborn as sns

In [56]:
# Import some additional libraries for ML tasks
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor
from sklearn.neural_network import MLPRegressor
from xgboost import XGBRegressor
#from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

from sklearn.metrics import mean_squared_error, r2_score

In [57]:
df = pd.read_pickle('..\\Dataset\\data\\B0005.pkl')
df

,type,ambient_temperature,time,data
0,charge,24,0.000,"{'Voltage_measured': [3.873017221300996, 3.479..."
1,discharge,24,8243.672,"{'Voltage_measured': [4.191491807505295, 4.190..."
2,charge,24,12574.063,"{'Voltage_measured': [3.3250546568448542, 3.00..."
3,discharge,24,23730.485,"{'Voltage_measured': [4.189773213846608, 4.188..."
4,charge,24,28042.891,"{'Voltage_measured': [3.3526036599987754, 3.03..."
...,...,...,...,...
611,discharge,24,4761863.438,"{'Voltage_measured': [4.18482689434833, 4.1843..."
612,charge,24,4769141.844,"{'Voltage_measured': [3.7032033475672854, 3.33..."
613,discharge,24,4779444.204,"{'Voltage_measured': [4.201968615940368, 4.200..."
614,impedance,24,4782370.719,{'Sense_current': [(839.7420654296875-31.55541...
615,charge,24,4831284.125,"{'Voltage_measured': [0.23635618415267867, 0.0..."

In [50]:
#df_charge['data'][0].keys()

dict_keys(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_charge', 'Voltage_charge', 'Time'])

In [11]:
df_discharge['data'][1].keys()

dict_keys(['Voltage_measured', 'Current_measured', 'Temperature_measured', 'Current_load', 'Voltage_load', 'Time', 'Capacity'])

In [46]:
#df_impedance['data'][40].keys()

dict_keys(['Sense_current', 'Battery_current', 'Current_ratio', 'Battery_impedance', 'Rectified_Impedance', 'Re', 'Rct'])

In [82]:
# Assuming df has a 'type' column that specifies the cycle type
def split_cell(df):
    df_charge = df[df['type'] == 'charge']
    df_discharge = df[df['type'] == 'discharge']
    df_impedance = df[df['type'] == 'impedance']

    df_charge = df_charge.reset_index(drop=True)  # Drops old index, new one is not saved in CSV
    df_discharge = df_discharge.reset_index(drop=True)
    df_impedance = df_impedance.reset_index(drop=True)
    
    return df_charge,df_discharge,df_impedence

In [64]:
df_charge = df_charge.reset_index(drop=True)  # Drops old index, new one is not saved in CSV
df_discharge = df_discharge.reset_index(drop=True)
df_impedance = df_impedance.reset_index(drop=True)

In [65]:
len(df_charge),len(df_discharge)

(170, 168)

In [66]:
df_discharge.shape

(168, 4)

In [67]:
df_discharge

,type,ambient_temperature,time,data
0,discharge,24,8243.672,"{'Voltage_measured': [4.191491807505295, 4.190..."
1,discharge,24,23730.485,"{'Voltage_measured': [4.189773213846608, 4.188..."
2,discharge,24,39168.766,"{'Voltage_measured': [4.188186735991303, 4.187..."
3,discharge,24,54499.454,"{'Voltage_measured': [4.188461118855572, 4.187..."
4,discharge,24,69907.782,"{'Voltage_measured': [4.188298524761055, 4.187..."
...,...,...,...,...
163,discharge,24,4656980.547,"{'Voltage_measured': [4.196640912532072, 4.195..."
164,discharge,24,4674146.047,"{'Voltage_measured': [4.1956235749123225, 4.19..."
165,discharge,24,4691567.000,"{'Voltage_measured': [4.195862008850563, 4.195..."
166,discharge,24,4761863.438,"{'Voltage_measured': [4.18482689434833, 4.1843..."
167,discharge,24,4779444.204,"{'Voltage_measured': [4.201968615940368, 4.200..."

In [68]:
df_charge['data'].apply(type).unique(), df_discharge['data'].apply(type).unique()

(array([<class 'dict'>], dtype=object), array([<class 'dict'>], dtype=object))

In [69]:
# Expand dictionary values into separate columns
df_charge_expanded = df_charge.join(pd.json_normalize(df_charge['data']))
df_discharge_expanded = df_discharge.join(pd.json_normalize(df_discharge['data']))

# Drop the original 'data' column as it's no longer needed
df_charge_expanded.drop(columns=['data'], inplace=True)
df_discharge_expanded.drop(columns=['data'], inplace=True)

# Display the first few rows
df_charge_expanded.head(), df_discharge_expanded.head()

(     type  ambient_temperature       time  \
 0  charge                   24      0.000
 1  charge                   24  12574.063
 2  charge                   24  28042.891
 3  charge                   24  43460.750
 4  charge                   24  58771.204

                                     Voltage_measured  \
 0  [3.873017221300996, 3.479393559379272, 4.00058...
 1  [3.3250546568448542, 3.001950570776504, 3.4346...
 2  [3.3526036599987754, 3.0358785775794024, 3.459...
 3  [3.378798976512954, 3.0661450551857485, 3.4855...
 4  [3.372870917439266, 3.0637656606174013, 3.4781...

                                     Current_measured  \
 0  [-0.001200660698297908, -4.030268477538787, 1....
 1  [0.00030204673114322896, -3.361982908688226, 1...
 2  [0.0019896423395958083, -3.384407789097242, 1....
 3  [-0.0022657924434299355, -3.4122633601213583, ...
 4  [-0.0005034579310428328, -3.403625146732859, 1...

                                 Temperature_measured  \
 0  [24.65535783391511, 24.66647981177477, 24.6753...
 1  [29.341850509195503, 29.335723138226193, 29.33...
 2  [29.553300732538816, 29.53875090986272, 29.539...
 3  [29.456340289732644, 29.436998002839278, 29.43...
 4  [29.4813335075363, 29.461954848628785, 29.4663...

                                       Current_charge  \
 0  [0.0, -4.036, 1.5, 1.5, 1.5, 1.498, 1.5, 1.5, ...
 1  [-0.002, -3.37, 1.498, 1.498, 1.498, 1.5, 1.49...
 2  [0.0, -3.387, 1.498, 1.498, 1.498, 1.498, 1.5,...
 3  [0.0, -3.413, 1.498, 1.5, 1.5, 1.498, 1.5, 1.5...
 4  [0.0, -3.406, 1.498, 1.498, 1.498, 1.498, 1.5,...

                                       Voltage_charge  \
 0  [0.003, 1.57, 4.726, 4.742, 4.753, 4.758, 4.76...
 1  [0.003, 1.414, 4.142, 4.18, 4.196, 4.207, 4.22...
 2  [0.003, 1.419, 4.175, 4.213, 4.229, 4.24, 4.25...
 3  [0.003, 1.425, 4.207, 4.24, 4.256, 4.267, 4.27...
 4  [0.003, 1.425, 4.202, 4.234, 4.25, 4.261, 4.27...

                                                 Time
 0  [0.0, 2.532, 5.5, 8.343999999999998, 11.125000...
 1  [0.0, 2.5159999999999982, 5.5, 8.3909999999999...
 2  [0.0, 2.546999999999997, 5.546999999999997, 8....
 3  [0.0, 2.5150000000000006, 5.453000000000003, 8...
 4  [0.0, 2.5, 5.453000000000003, 8.28099999999999...  ,
         type  ambient_temperature       time  \
 0  discharge                   24   8243.672
 1  discharge                   24  23730.485
 2  discharge                   24  39168.766
 3  discharge                   24  54499.454
 4  discharge                   24  69907.782

                                     Voltage_measured  \
 0  [4.191491807505295, 4.190749067776103, 3.97487...
 1  [4.189773213846608, 4.188881380279099, 3.97915...
 2  [4.188186735991303, 4.187198338393574, 3.97999...
 3  [4.188461118855572, 4.187752210174129, 3.98161...
 4  [4.188298524761055, 4.187384730878918, 3.98225...

                                     Current_measured  \
 0  [-0.004901589207462691, -0.0014780055516425076...
 1  [2.125117981080765e-05, -0.0008794712663407272...
 2  [-0.0017540301662326099, -0.001791647748693578...
 3  [-0.0027750361294468047, 0.0002337127076932362...
 4  [-0.007980866803888688, 0.001701454824503414, ...

                                 Temperature_measured  \
 0  [24.330033885570543, 24.325993424022467, 24.38...
 1  [24.697751935729325, 24.685948163596, 24.73813...
 2  [24.734266163954402, 24.74050014862512, 24.791...
 3  [24.65423646922845, 24.652243741292516, 24.697...
 4  [24.524796959348127, 24.518700434435164, 24.57...

                                         Current_load  \
 0  [-0.0006, -0.0006, -1.9982, -1.9982, -1.9982, ...
 1  [-0.0006, -0.0006, -1.9984, -1.9982, -1.9984, ...
 2  [-0.0006, -0.0006, -1.9982, -1.9982, -1.9982, ...
 3  [-0.0006, -0.0006, -1.9982, -1.9982, -1.9982, ...
 4  [-0.0006, -0.0006, -1.9982, -1.9982, -1.9982, ...

                                         Voltage_load  \
 0  [0.0, 4.206, 3.062, 3.03, 3.011, 2.991, 2.977,...
 1  [0.0, 4.204, 3.056, 3.024, 3.003, 2.983, 2.973...
 2  [0.0, 4.203, 3.055, 3.023, 3.0, 2.981, 2.97, 2...
 3  [0.0, 4.203, 3.055, 3.023, 2.999, 2.982, 2.97,...
 4  [0.0, 4.203, 3.056, 3.025, 3.0, 2.984, 2.973, ...

                                                 Time  Capacity
 0  [0.0, 16.781, 35.702999999999996, 53.781, 71.9...  1.856487
 1  [0.0, 16.672, 35.703, 53.828, 71.891, 90.047, ...  1.846327
 2  [0.0, 16.796999999999997, 35.766, 53.891, 72.0...  1.835349
 3  [0.0, 16.766000000000002, 35.75, 53.813, 72.04...  1.835263
 4  [0.0, 16.719, 35.656000000000006, 53.859, 72.0...  1.834646  )

In [70]:
df_charge_expanded.iloc[:1]

,type,ambient_temperature,time,Voltage_measured,Current_measured,Temperature_measured,Current_charge,Voltage_charge,Time
0,charge,24,0.0,"[3.873017221300996, 3.479393559379272, 4.00058...","[-0.001200660698297908, -4.030268477538787, 1....","[24.65535783391511, 24.66647981177477, 24.6753...","[0.0, -4.036, 1.5, 1.5, 1.5, 1.498, 1.5, 1.5, ...","[0.003, 1.57, 4.726, 4.742, 4.753, 4.758, 4.76...","[0.0, 2.532, 5.5, 8.343999999999998, 11.125000..."

In [71]:
df_discharge_expanded.iloc[[123]]

,type,ambient_temperature,time,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time,Capacity
123,discharge,24,3885177.969,"[4.196688955833435, 4.19602274379362, 3.983219...","[-0.0020447392506862732, 0.001194477195621937,...","[24.345219404030782, 24.335820690902352, 24.35...","[0.0006, 0.0006, 1.9982, 1.9982, 1.9982, 1.998...","[0.0, 4.211, 2.962, 2.953, 2.946, 2.935, 2.925...","[0.0, 9.390999999999998, 19.5, 28.875, 38.235,...",1.401204

In [72]:
df_discharge_expanded["Voltage_measured"].apply(np.mean)

0      3.529829
1      3.537320
2      3.543737
3      3.543666
4      3.542343
         ...
163    3.466462
164    3.468509
165    3.466806
166    3.471071
167    3.475472
Name: Voltage_measured, Length: 168, dtype: float64

In [73]:
from scipy.stats import f_oneway
import numpy as np

# Extract relevant features for charge data
df_charge_extracted = df_charge_expanded.copy()
df_charge_extracted["Voltage_measured"] = df_charge_extracted["Voltage_measured"].apply(np.mean)
df_charge_extracted["Current_measured"] = df_charge_extracted["Current_measured"].apply(np.mean)
df_charge_extracted["Temperature_measured"] = df_charge_extracted["Temperature_measured"].apply(np.mean)
df_charge_extracted["Current_charge"] = df_charge_extracted["Current_charge"].apply(np.mean)
df_charge_extracted["Voltage_charge"] = df_charge_extracted["Voltage_charge"].apply(np.mean)

# Extract relevant features for discharge data
df_discharge_extracted = df_discharge_expanded.copy()
df_discharge_extracted["Voltage_measured"] = df_discharge_extracted["Voltage_measured"].apply(np.mean)
df_discharge_extracted["Current_measured"] = df_discharge_extracted["Current_measured"].apply(np.mean)
df_discharge_extracted["Temperature_measured"] = df_discharge_extracted["Temperature_measured"].apply(np.mean)
df_discharge_extracted["Current_load"] = df_discharge_extracted["Current_load"].apply(np.mean)
df_discharge_extracted["Voltage_load"] = df_discharge_extracted["Voltage_load"].apply(np.mean)

# The target variable for RUL prediction is 'Capacity' (only in discharge data)
df_discharge_extracted["Capacity"] = df_discharge_extracted["Capacity"]

In [74]:
df_discharge_extracted

,type,ambient_temperature,time,Voltage_measured,Current_measured,Temperature_measured,Current_load,Voltage_load,Time,Capacity
0,discharge,24,8243.672,3.529829,-1.818702,32.572328,-1.805570,2.404944,"[0.0, 16.781, 35.702999999999996, 53.781, 71.9...",1.856487
1,discharge,24,23730.485,3.537320,-1.817560,32.725235,-1.804583,2.399260,"[0.0, 16.672, 35.703, 53.828, 71.891, 90.047, ...",1.846327
2,discharge,24,39168.766,3.543737,-1.816487,32.642862,-1.803575,2.397969,"[0.0, 16.796999999999997, 35.766, 53.891, 72.0...",1.835349
3,discharge,24,54499.454,3.543666,-1.825589,32.514876,-1.812863,2.408289,"[0.0, 16.766000000000002, 35.75, 53.813, 72.04...",1.835263
4,discharge,24,69907.782,3.542343,-1.826114,32.382349,-1.812876,2.408505,"[0.0, 16.719, 35.656000000000006, 53.859, 72.0...",1.834646
...,...,...,...,...,...,...,...,...,...,...
163,discharge,24,4656980.547,3.466462,-1.674488,33.275688,1.661799,2.073168,"[0.0, 9.343, 19.483999999999998, 28.7650000000...",1.293464
164,discharge,24,4674146.047,3.468509,-1.667447,33.320678,1.655086,2.064189,"[0.0, 9.359000000000002, 19.562000000000005, 2...",1.288003
165,discharge,24,4691567.000,3.466806,-1.667470,33.373150,1.655103,2.062717,"[0.0, 9.313000000000002, 19.469, 28.797, 38.14...",1.287453
166,discharge,24,4761863.438,3.471071,-1.688898,33.713519,1.676430,2.107460,"[0.0, 9.375, 19.593999999999998, 28.9839999999...",1.309015
167,discharge,24,4779444.204,3.475472,-1.697928,33.865318,1.685264,2.120230,"[0.0, 9.328, 19.515, 28.936999999999998, 38.31...",1.325079

In [75]:


# Perform One-Way ANOVA test to determine feature importance
anova_results = {}
features = ["Voltage_measured", "Current_measured", "Temperature_measured", "Current_load", "Voltage_load"]

for feature in features:
    f_stat, p_value = f_oneway(df_discharge_extracted[feature], df_discharge_extracted["Capacity"])
    anova_results[feature] = (f_stat, p_value)

# Display ANOVA results
print(anova_results)

{'Voltage_measured': (17013.511265582838, 1.435453730953985e-288), 'Current_measured': (44184.742635208124, 0.0), 'Temperature_measured': (300141.7299445223, 0.0), 'Current_load': (17.699387088083817, 3.3279550727959036e-05), 'Voltage_load': (1564.553369047109, 4.4723232961266884e-128)}

In [77]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score

# Select important features for training
features = ["Voltage_measured", "Current_measured", "Temperature_measured", "Voltage_load", "Current_load"]
target = "Capacity"

# Split data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(df_discharge_extracted[features], df_discharge_extracted[target], test_size=0.2, random_state=42)

# **1️⃣ Train Random Forest Model**
rf_model = RandomForestRegressor(n_estimators=100, max_depth=10, random_state=42)
rf_model.fit(X_train, y_train)
rf_preds = rf_model.predict(X_test)

# **2️⃣ Train Support Vector Machine (SVM) Model**
scaler = StandardScaler()  # Normalize features for SVM
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

svm_model = SVR(kernel="rbf", C=10)
svm_model.fit(X_train_scaled, y_train)
svm_preds = svm_model.predict(X_test_scaled)

# **Evaluate Models**
rf_mse = mean_squared_error(y_test, rf_preds)
rf_r2 = r2_score(y_test, rf_preds)

svm_mse = mean_squared_error(y_test, svm_preds)
svm_r2 = r2_score(y_test, svm_preds)

# Display results
print("Random Forest Results: MSE =", rf_mse, ", R² =", rf_r2)
print("SVM Results: MSE =", svm_mse, ", R² =", svm_r2)

Random Forest Results: MSE = 0.00022182022745065332 , R² = 0.9939809647488913
SVM Results: MSE = 0.005967853552699457 , R² = 0.8380638171731069

In [79]:
svm_preds

array([1.42651626, 1.72155583, 1.51972686, 1.71600167, 1.40671389,
       1.38850718, 1.38782164, 1.72147591, 1.54640097, 1.71324582,
       1.73201894, 1.39409342, 1.4763055 , 1.70638834, 1.69091592,
       1.62898575, 1.72152056, 1.52125831, 1.665565  , 1.52742397,
       1.75529105, 1.72968426, 1.72156707, 1.72716974, 1.74388088,
       1.75515579, 1.63104211, 1.57678012, 1.66573388, 1.7184876 ,
       1.72525036, 1.71707627, 1.39448721, 1.50356629])

In [81]:
df = pd.read_pickle('..\\Dataset\\data\\B0018.pkl')
df

,type,ambient_temperature,time,data
0,charge,24,0.000,"{'Voltage_measured': [3.8657128300167622, 3.44..."
1,impedance,24,8188.875,{'Sense_current': [(832.7495727539062-27.37719...
2,discharge,24,10123.125,"{'Voltage_measured': [4.188108651124536, 4.188..."
3,impedance,24,13639.578,{'Sense_current': [(835.9423217773438-23.70555...
4,charge,24,21208.500,"{'Voltage_measured': [3.3426495868217896, 2.96..."
...,...,...,...,...
314,impedance,24,3676078.687,{'Sense_current': [(828.6859741210938-23.83417...
315,charge,24,3677991.968,"{'Voltage_measured': [3.6856472494696737, 3.32..."
316,discharge,24,3688514.546,"{'Voltage_measured': [4.18481632859354, 4.1852..."
317,charge,24,3691366.078,"{'Voltage_measured': [3.4951893990613723, 3.17..."
318,discharge,24,3701433.765,"{'Voltage_measured': [4.185409109511607, 4.185..."